// This file would typically be auto-generated by Sanity TypeGen
// Run: npx sanity typegen generate

export interface SanityDocument {
  _id: string
  _type: string
  _createdAt: string
  _updatedAt: string
  _rev: string
}

export interface Slug {
  _type: 'slug'
  current: string
}

export interface Image {
  _type: 'image'
  asset: {
    _ref: string
    _type: 'reference'
  }
  alt?: string
  caption?: string
  attribution?: string
  url?: string
  metadata?: {
    dimensions: {
      width: number
      height: number
      aspectRatio: number
    }
    lqip?: string
    palette?: any
    blurhash?: string
  }
}

export interface SEO {
  metaTitle?: string
  metaDescription?: string
  keywords?: string[]
  canonicalUrl?: string
  ogTitle?: string
  ogDescription?: string
  ogImage?: Image
  twitterCard?: 'summary' | 'summary_large_image' | 'app' | 'player'
  noIndex?: boolean
  noFollow?: boolean
  structuredData?: string
}

export interface Project extends SanityDocument {
  _type: 'project'
  title: string
  slug: Slug
  featured?: boolean
  order?: number
  client?: string
  projectType: 'web-app' | 'mobile-app' | 'ecommerce' | 'saas' | 'api' | 'open-source' | 'design-system' | 'other'
  status?: 'in-development' | 'live' | 'completed' | 'archived'
  startDate?: string
  endDate?: string
  summary: string
  description?: any // BlockContent
  role?: string
  responsibilities?: string[]
  mainImage: Image
  gallery?: ImageGallery
  techStack?: TechStack
  features?: Feature[]
  challenges?: Challenge[]
  solutions?: Solution[]
  outcomes?: Outcome[]
  metrics?: ProjectMetrics
  caseStudy?: CaseStudy
  liveUrl?: string
  githubUrl?: string
  demoUrl?: string
  videoDemo?: VideoEmbed
  testimonial?: Testimonial
  relatedProjects?: Project[]
  categories?: Category[]
  tags?: string[]
  seo?: SEO
  publishedAt: string
}

export interface Article extends SanityDocument {
  _type: 'article'
  title: string
  slug: Slug
  featured?: boolean
  author: Author
  coAuthors?: Author[]
  excerpt: string
  mainImage: Image
  content: any // BlockContent
  categories: Category[]
  tags?: string[]
  readingTime?: number
  difficulty?: 'beginner' | 'intermediate' | 'advanced' | 'expert'
  series?: {
    title: string
    order: number
    total: number
  }
  relatedArticles?: Article[]
  relatedProjects?: Project[]
  resources?: {
    title: string
    url: string
    type: string
  }[]
  codeExamples?: string
  callToAction?: CallToAction
  enableComments?: boolean
  seo?: SEO
  publishedAt: string
  updatedAt?: string
  status: 'draft' | 'review' | 'scheduled' | 'published' | 'archived'
}

export interface Author extends SanityDocument {
  _type: 'author'
  name: string
  slug: Slug
  email: string
  bio?: string
  avatar?: Image
  role?: string
  socialLinks?: {
    twitter?: string
    github?: string
    linkedin?: string
    website?: string
  }
}

export interface Category extends SanityDocument {
  _type: 'category'
  title: string
  slug: Slug
  description?: string
  color?: { hex: string }
  icon?: Image
  parent?: Category
}

export interface Testimonial extends SanityDocument {
  _type: 'testimonial'
  name: string
  role: string
  company?: string
  companyUrl?: string
  testimonial: string
  rating: number
  image?: Image
  project?: Project
  featured?: boolean
  date?: string
  linkedin?: string
  verified?: boolean
}

export interface Skill extends SanityDocument {
  _type: 'skill'
  name: string
  category: 'frontend' | 'backend' | 'database' | 'devops' | 'mobile' | 'cloud' | 'tools' | 'soft' | 'other'
  proficiency: number
  yearsOfExperience?: number
  icon?: Image
  color?: { hex: string }
  featured?: boolean
  order?: number
  certifications?: Certification[]
  projects?: Project[]
}

export interface Experience extends SanityDocument {
  _type: 'experience'
  position: string
  company: string
  companyUrl?: string
  companyLogo?: Image
  location?: string
  employmentType?: string
  startDate: string
  endDate?: string
  current?: boolean
  description?: string
  responsibilities?: string[]
  achievements?: Achievement[]
  technologies?: string[]
  skills?: Skill[]
  projects?: Project[]
  order?: number
}

export interface Education extends SanityDocument {
  _type: 'education'
  degree: string
  field: string
  institution: string
  institutionUrl?: string
  location?: string
  startDate?: string
  endDate?: string
  gpa?: string
  honors?: string[]
  relevantCourses?: string[]
  description?: string
  order?: number
}

export interface Certification extends SanityDocument {
  _type: 'certification'
  title: string
  issuer: string
  issuerUrl?: string
  credentialId?: string
  credentialUrl?: string
  issueDate: string
  expiryDate?: string
  doesNotExpire?: boolean
  description?: string
  logo?: Image
  skills?: Skill[]
  featured?: boolean
}

// Object Types
export interface ProjectMetrics {
  performanceImprovement?: string
  userGrowth?: string
  revenueImpact?: string
  efficiency?: string
  codeQuality?: {
    coverage?: number
    maintainabilityIndex?: string
    technicalDebt?: string
  }
  teamSize?: number
  duration?: string
  budget?: string
  customMetrics?: {
    label: string
    value: string
    icon?: string
  }[]
  lighthouse?: {
    performance?: number
    accessibility?: number
    bestPractices?: number
    seo?: number
  }
}

export interface TechStack {
  frontend?: TechItem[]
  backend?: TechItem[]
  database?: TechItem[]
  devops?: TechItem[]
  tools?: ToolItem[]
}

export interface TechItem {
  name: string
  version?: string
  icon?: Image
}

export interface ToolItem {
  name: string
  purpose?: string
  icon?: Image
}

export interface CaseStudy {
  overview?: any // BlockContent
  process?: {
    research?: any
    planning?: any
    design?: any
    development?: any
    testing?: any
    deployment?: any
  }
  timeline?: Timeline
  learnings?: {
    title: string
    description?: string
  }[]
  nextSteps?: string[]
}

export interface ImageGallery {
  title?: string
  images: Image[]
  layout?: 'grid' | 'masonry' | 'carousel' | 'slider'
  columns?: number
  showCaptions?: boolean
  enableLightbox?: boolean
}

export interface VideoEmbed {
  title?: string
  platform: 'youtube' | 'vimeo' | 'loom' | 'custom'
  url: string
  videoId?: string
  thumbnail?: Image
  aspectRatio?: string
  autoplay?: boolean
  loop?: boolean
  muted?: boolean
  controls?: boolean
  caption?: string
}

export interface CallToAction {
  title: string
  text?: string
  primaryButton?: {
    label: string
    url?: string
    page?: Project | Article
    openInNewTab?: boolean
  }
  secondaryButton?: {
    label: string
    url?: string
    page?: Project | Article
    openInNewTab?: boolean
  }
  style?: 'default' | 'centered' | 'card' | 'banner'
  backgroundImage?: Image
  backgroundColor?: { hex: string }
}

export interface Timeline {
  title?: string
  events: {
    date: string
    title: string
    description?: string
    milestone?: boolean
    icon?: string
    color?: { hex: string }
  }[]
}

export interface Achievement {
  title: string
  description?: string
  metric?: string
  date?: string
  icon?: string
}

export interface Feature {
  title: string
  description: string
  icon?: string
  image?: Image
  technical?: string
}

export interface Challenge {
  title: string
  description: string
  impact?: string
  severity?: 'low' | 'medium' | 'high' | 'critical'
}

export interface Solution {
  title: string
  description: string
  approach?: string
  technologies?: string[]
  effectiveness?: string
}

export interface Outcome {
  title: string
  description: string
  metric?: string
  category?: 'performance' | 'ux' | 'business' | 'technical' | 'process'
  icon?: string
}